site_name: Manual de HMV Tools
site_description: Documentación oficial y guía de usuario para los scripts de Revit de HMV.
theme:
  name: material
  palette:
    scheme: default
    primary: blue
    accent: yellow
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Inicio: index.md
  - Herramientas DWG: dwg.md
  - Control de Familias: family-control.md
  - Herramientas de Anotación: annotation.md
  - Auditoría: audit.md