site_name: Manual de HMV Tools
site_description: Documentación oficial y guía de usuario para los scripts de Revit de HMV.

theme:
  name: material
  language: es
  logo: img/HMVlogo.png
  favicon: img/HMVlogo.png
  palette:
   
    - scheme: slate
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
        
    
    - scheme: default
      primary: white
      accent: yellow
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
  
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.top
  
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Inicio: index.md
  - Herramientas DWG: dwg.md
  - Control de Familias: family-control.md
  - Herramientas de Anotación: annotation.md
  - Auditoría: audit.md
  

markdown_extensions:
  - attr_list